name: Desplegar Sitio en Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: 1. Limpiar directorio en el servidor (usando SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Borrando contenido antiguo de /var/www/html..."
            # Usamos sudo directamente, que sabemos que funciona sin contraseña
            sudo rm -rf /var/www/html/*

      - name: 2. Copiar nuevos archivos al servidor (usando SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/var/www/html"
          # NOTA: Hemos quitado la línea 'rm: true' de aquí

      - name: 3. Verificar despliegue en el servidor (usando SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Verificando el nuevo contenido..."
            ls -la /var/www/html
