name: Desplegar Sitio en Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Copiar archivos al servidor por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Limpiando directorio de destino..."
            sudo rm -rf /var/www/html/*
            echo "Copiando archivos del nuevo sitio..."
            sudo cp -rT ${{ github.workspace }} /var/www/html
            echo "Despliegue completado."
